import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const root = process.cwd();
const ignoredDirectories = new Set([".git", "dist", "node_modules"]);

async function collectFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return ignoredDirectories.has(entry.name) ? [] : collectFiles(path);
    return [relative(root, path).replaceAll("\\", "/")];
  }));
  return files.flat().sort();
}

const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
const sourceFiles = (await collectFiles(join(root, "src"))).filter((file) => /\.(ts|tsx)$/.test(file));
const scripts = Object.entries(packageJson.scripts).sort(([a], [b]) => a.localeCompare(b));
const markdown = `# Project Snapshot

This file is generated by \`npm run docs:generate\`. Do not edit it manually.

## Package Scripts

| Command | Purpose |
| --- | --- |
${scripts.map(([name, command]) => `| \`npm run ${name}\` | \`${command}\` |`).join("\n")}

## Source Files

${sourceFiles.map((file) => `- \`${file}\``).join("\n")}

## Agent Entry Points

- \`AGENTS.md\`: shared repository instructions
- \`CLAUDE.md\`: Claude Code pointer
- \`.roo/rules/oom-project.md\`: Roo Code pointer
- \`docs/ARCHITECTURE.md\`: system boundaries
- \`docs/TRAINING_SYSTEM.md\`: Course × Level and STEP 1-6 contracts
- \`docs/CONTENT_AUTHORING.md\`: Course and content workflow
- \`docs/TTS_AUDIO_PIPELINE.md\`: static-first TTS workflow
- \`docs/ROUTING.md\`: view ownership and navigation map
- \`docs/DEPLOYMENT.md\`: Pages and static-hosting workflow
`;

const outputPath = join(root, "docs", "PROJECT_SNAPSHOT.md");
const output = `${markdown}\n`;
if (process.argv.includes("--check")) {
  const existing = await readFile(outputPath, "utf8").catch(() => "");
  if (existing !== output) {
    console.error("Documentation snapshot is out of date. Run: npm run docs:generate");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, output, "utf8");
  console.log(`Updated ${relative(root, outputPath)}`);
}
