import { AlertTriangle, BadgeCheck, CheckCircle2, Clock3, ShieldCheck } from "lucide-react";
import { dayOfExamRules, examProcess, identityWarnings, type ExamGuideSection } from "../../data/examGuideContent";
import { Badge } from "../ui/Badge";
import { Card } from "../ui/Card";
import { ExamGuideTabs } from "./ExamGuideTabs";

type ExamGuideDayProps = { onSectionChange: (section: ExamGuideSection) => void };

export function ExamGuideDay({ onSectionChange }: ExamGuideDayProps) {
  const orientation = examProcess.filter((item) => item.phase === "orientation");
  const test = examProcess.filter((item) => item.phase === "test");

  return (
    <div className="space-y-6">
      <ExamGuideTabs activeSection="exam-day" onSectionChange={onSectionChange} />
      <section className="border-l-4 border-indigo-500 pl-4"><Badge tone="indigo">신분증 · 입실 · 진행</Badge><h1 className="mt-3 text-2xl font-bold text-zinc-950 dark:text-white sm:text-3xl">시험 당일은 시간표처럼 보고 준비하세요.</h1><p className="mt-3 text-sm leading-7 text-zinc-600 dark:text-zinc-300">입실 시간과 규정 신분증은 답변 실력만큼 중요합니다. 아래 흐름을 한 번 훑고, 전날에는 신분증 원본과 센터 안내를 다시 확인하세요.</p></section>

      <Card className="overflow-hidden p-0">
        <div className="border-b border-zinc-200 bg-zinc-50 px-5 py-4 dark:border-zinc-800 dark:bg-zinc-950"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-indigo-600 dark:text-indigo-300" /><h2 className="text-lg font-bold text-zinc-950 dark:text-white">입실 통제와 시험 시간</h2></div><p className="mt-1 text-sm text-zinc-600 dark:text-zinc-300">예시가 10:00 시험인 경우입니다. 센터 안내를 최종 기준으로 확인하세요.</p></div>
        <div className="p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-[0.8fr_2.2fr]"><div className="rounded-md border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><p className="text-xs font-semibold text-zinc-500 dark:text-zinc-400">입실 구간</p><p className="mt-2 text-2xl font-bold text-zinc-950 dark:text-white">9:50–9:59</p><p className="mt-2 text-sm leading-6 text-zinc-600 dark:text-zinc-300">시험 시작 10분 전까지 명단과 신분 확인을 거쳐 입실합니다.</p></div><div className="rounded-md border border-indigo-200 bg-indigo-50/50 p-4 dark:border-indigo-900 dark:bg-indigo-950/30"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-indigo-700 dark:text-indigo-300">10:00 이후</p><Badge tone="indigo">오리엔테이션 + 본시험</Badge></div><div className="relative mt-6 h-3 rounded-full bg-indigo-200 dark:bg-indigo-900"><div className="absolute left-0 top-0 h-3 w-[33%] rounded-l-full bg-zinc-400" /><div className="absolute left-[33%] top-0 h-3 w-[67%] rounded-r-full bg-indigo-600" /><span className="absolute left-[33%] top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-white bg-indigo-600 dark:border-zinc-900" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-lg font-bold text-zinc-950 dark:text-white">시험 시작 정시</p><p className="mt-1 text-sm text-zinc-600 dark:text-zinc-300">입실 통제 및 지각 판정</p></div><div><p className="text-lg font-bold text-zinc-950 dark:text-white">약 60분</p><p className="mt-1 text-sm text-zinc-600 dark:text-zinc-300">OT 약 20분 + 응시 약 40분</p></div></div></div></div></div>
      </Card>

      <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><BadgeCheck className="h-5 w-5 text-indigo-600 dark:text-indigo-300" /><h2 className="text-lg font-bold text-zinc-950 dark:text-white">오리엔테이션부터 2차 세션까지</h2></div><p className="mt-2 text-sm leading-6 text-zinc-600 dark:text-zinc-300">질문은 문항마다 두 번 들을 수 있고, 답변 시간에는 별도의 제한이 없습니다. 다만 전체 응시 흐름을 고려해 한 문제에 지나치게 오래 머무르지 않는 편이 좋습니다.</p><div className="mt-5 rounded-md bg-zinc-100 p-4 sm:p-6 dark:bg-zinc-950"><div className="flex items-center gap-2 text-xs font-semibold text-zinc-500 dark:text-zinc-400"><span className="h-2 w-2 rounded-full bg-zinc-400" />오리엔테이션 <span className="ml-3 h-2 w-2 rounded-full bg-indigo-600" />본시험</div><div className="mt-5 grid gap-3 lg:grid-cols-4">{orientation.map((item) => <div className="rounded-md bg-white p-4 shadow-sm dark:bg-zinc-900" key={item.step}><span className="grid h-7 w-7 place-items-center rounded-full bg-zinc-900 text-xs font-bold text-white dark:bg-zinc-700">{item.step}</span><p className="mt-3 text-sm font-bold text-zinc-950 dark:text-white">{item.title}</p><p className="mt-2 text-xs leading-5 text-zinc-600 dark:text-zinc-300">{item.detail}</p></div>)}</div><div className="my-5 border-t-2 border-dashed border-indigo-300 dark:border-indigo-800" /><div className="grid gap-3 lg:grid-cols-3">{test.map((item) => <div className="rounded-md bg-indigo-600 p-4 text-white shadow-sm" key={item.step}><span className="grid h-7 w-7 place-items-center rounded-full bg-white/20 text-xs font-bold">{item.step}</span><p className="mt-3 text-sm font-bold">{item.title}</p><p className="mt-2 text-xs leading-5 text-indigo-100">{item.detail}</p></div>)}</div></div></Card>

      <section className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-rose-600" /><h2 className="text-base font-bold text-zinc-950 dark:text-white">규정 신분증 핵심</h2></div><ul className="mt-4 space-y-3">{identityWarnings.slice(0, 2).map((warning) => <li className="flex gap-2 text-sm leading-6 text-zinc-600 dark:text-zinc-300" key={warning}><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-rose-500" />{warning}</li>)}</ul></Card><Card className="border-amber-200 bg-amber-50 p-5 dark:border-amber-900 dark:bg-amber-950"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-300" /><h2 className="text-base font-bold text-amber-900 dark:text-amber-100">당일 체크</h2></div><div className="mt-4 space-y-3">{dayOfExamRules.slice(0, 3).map((rule) => <div key={rule.title}><p className="text-sm font-bold text-amber-900 dark:text-amber-100">{rule.title}</p><p className="mt-1 text-sm leading-6 text-amber-800 dark:text-amber-200">{rule.detail}</p></div>)}</div></Card></section>
    </div>
  );
}
